---
- name: Diplom project docker deploy
  hosts: diplom
  gather_facts: true
  become: false
  become_method: sudo
  vars_files: diplom_vars.yml
  tasks:
    - import_tasks: install_docker.yml
    - import_tasks: conf_docker.yml
    - import_tasks: run_docker.yml

- hosts: localhost
  vars_files:
    - secrets.yml
  tasks:
    - name: Print DB password
      debug:
        msg: "DB password is {{ db_password }}"

- name: Update and install Apache2 and configure UFW
  hosts: diplom
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present
    - name: Allow all access to tcp port 80
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp
    - name: Allow all access to tcp port 443
      community.general.ufw:
        rule: allow
        port: '443'
        proto: tcp
    - name: Check UFW status
      command: sudo ufw status
      register: ufw_status

    - debug:
        var: ufw_status.stdout

