---
- name: Diplom project docker deploy
  hosts: diplom
  gather_facts: true
  become: false
  become_method: sudo
  vars_files: diplom_vars.yml
  tasks:
    - import_tasks: install_docker.yml
    - import_tasks: conf_docker.yml
    - import_tasks: run_docker.yml
- hosts: localhost
  vars_files:
    - secrets.yml
  tasks:
    - name: Print DB password
      debug:
        msg: "DB password is {{ db_password }}"





